apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment   # mention any name
  labels:
    app: nginx   # mention any name 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx   # mention any name
  template:
    metadata:
      labels:
        app: nginx   # mention any name
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2   # use your image id accoring to your project
        ports:
        - containerPort: 80   # use any port number ex: 8000
