apiVersion: v1
kind: Service
metadata:
  name: my-service  # mention any name
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80   # ex: deployment.yml uses the 8000 we have use same here
      nodePort: 30007
